services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    init: true
    command:
      - sleep
      - inf
  s3:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    volumes:
      - type: volume
        source: s3-data
        target: /data
    environment:
      - MINIO_ROOT_USER=super
      - MINIO_ROOT_PASSWORD=secretsecret
      - MINIO_DOMAIN=s3
    networks:
      default:
        aliases:
          - test.s3
          - test2.s3
    command:
      - server
      - /data
      - --console-address
      - :9001

volumes:
  s3-data:
